### ISSUE TITLE
Double-click video opens forced MPC-BE without video file in commandline

### ISSUE THREAD

**Issue by MrSmite** [sandboxie-plus/Sandboxie#3791]
### Describe what you noticed and did

I have MPC-BE set as default for audio/video in windows 10. In Sandboxie-Plus I have the following setting:

Forced program: mpc-be64.exe
Resource Access:  Program: mpc-be64.exe  Access: open   Path: \*.\*

When I double-click a video file in Explorer, MPC-BE opens in the sandbox but it does not include the video file on the commandline so no file is opened. If I right-click the video file in Explorer and choose "Run Sandboxed", MPC-BE opens in the sandbox and properly plays the video file.

Notes:

* This does not happen with MPC-HC but this player is very old and unstable
* When observing the Sandboxie GUI, I see different behavior for different open methods:

1. Double-Click opens two instances of MPC-BE64.exe in the sandbox and after a few seconds, terminates the first process. The second remaining process contains no file to play. This also leaves the spinning mouse pointer in Windows and has a chance to crash Explorer if you try to close it.

2. Right-click and "open in sandbox" only opens a single instance of MPC-BE64.exe which contains the file and plays properly

### How often did you encounter it so far?

Always

### Expected behavior

Double-clicking a video file should open the forced program in the sandbox and play

### Affected program

MPC-BE64.exe

### Download link

https://sourceforge.net/projects/mpcbe/files/MPC-BE/Release%20builds/

### Where is the program located?

The program is installed only outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

1.13.4 64-bit

### Is it a new installation of Sandboxie?

I recently did a new clean installation.

### Is it a regression from previous versions?

Don't know

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 10 Pro H22 64-bit

### In which Windows account you have this problem?

A local account (Administrator).

### Please mention any installed security software

Norton 360

### Did you previously enable some security policy settings outside Sandboxie?

No

**Comment by offhub** [comment]
Please test to see if `NoRestartOnPAC=y` solves your issue.

**Comment by MrSmite** [comment]
> NoRestartOnPAC=y

Just checked the sandbox's INI and that setting already exists.

Also, I just noticed neither instance of MPC-BE that open in the sandbox contain the filename in the path/command line section of the main UI. When opened as I mentioned above, you will see the full path to mpc-be and the audio/video file listed there.

Further testing shows that MPC-BE offers two right-click options on a video file: "Play with MPC-BE" or "Add to MPC-BE playlist". In both cases, the double instance of MPC-BE opens but no file is on the commandline. In the second instance, viewing the playlist is empty.

As for the Explorer issue, if you close MPC-BE the cursor will continue to "wait" and if you click on a file the whole window will turn white. If you attempt to close it at this point, it will crash. If you wait about 30 to 60 seconds and don't click anything, it will return to normal.

**Comment by offhub** [comment]
Sorry, I wrote it wrong. Try changing the `PAC` section at the end of that setting to `PCA`.

```
NoRestartOnPCA=y
```

**Comment by MrSmite** [comment]
That changed it so only one instance of MPC-BE64.exe opens but it still does not have the filename on the commandline so nothing plays.

**Comment by xsmolasses** [comment]
My inference-based guess is:

Presence of (thereby "registered" ?), e.g., HKEY_CLASSES_ROOT\mpc-be64.mp4\shell\open\DropTarget" with CLSID,
makes Explorer unintuitively open with this drag-and-Drop handler, which communicates via COM interface.

But that's between Explorer and MPC-BE's shell extension, the latter which, when the setting is not wanting multiple MPC-BE instances, -- and failing to find any, starts a new MPC-BE instance -- then waits around to find (foreground-most [recently active] by intrinsic z-order), a MPC-BE window via its Class name, then sends (blocking for a "reply") Window Message, WM_COPYDATA, consisting of filename argument(s) that is parsed as if passed in via command line parameters and not processed by user "MPC" API commands through the same message channel.

The issue is Sandboxie prefixes Window Class names like Sandbox:YOUR_SANDBOX_NAME:REAL_CLASS_NAME and MPC-BE's shell extension cannot find an exact match, so we must disable Sandboxie's renaming of Window Class names.
```
#OpenWinClass=#
# which does just that, doesn't rename Window Classes;
# and applies to all Window Class names within a Sandbox.
# or better yet, be explicit:
OpenWinClass=MPC-BE
# not renaming given Class name is apparently a side-effect of this form,
# which is intended for messages outbound to processes not sandboxed.
```

**Comment by MrSmite** [comment]
Since every method of opening it with Start.exe works, would it not be possible to capture the double-clicked forced program and reopen it with Start.exe?

**Comment by offhub** [comment]
This setting should fix the issue.

```
NoRenameWinClass=mpc-be64.exe,*
```

**Comment by MrSmite** [comment]
Is there a way to test this locally or does it require a new build? I opened the INI to edit it and it says:

> # A template section (official or local) may only contain the
> # following settings:
> #
> #     Tmpl.Title
> #     Tmpl.Class
> #     Tmpl.Url
> #     Tmpl.Comment
> #     Tmpl.Scan
> #     OpenFilePath
> #     OpenPipePath
> #     ReadFilePath
> #     ClosedFilePath
> #     OpenKeyPath
> #     ReadKeyPath
> #     ClosedKeyPath
> #     OpenIpcPath
> #     ClosedIpcPath
> #     OpenWinclass
> #     OpenClsid
> #     RecoverFolder
> #     AutoRecoverIgnore
> #     ForceProcess
> #     ForceFolder
> #     OpenProtectedStorage
> #     OpenCredentials
> #     ProcessGroup
> #
> # Any other settings must not be used, as it may confuse the
> # Sandbox Control program.

Notice that **_NoRenameWinClass_** is not allowed. I copied the MPC-BE section from the merge here but it didn't solve the issue.

**Comment by offhub** [comment]
Have you enabled the `MPC-BE_Force` template? If you haven't enabled it, add one of the above settings to your sandbox configuration.

**Comment by MrSmite** [comment]
Thank you, I hadn't done that because I still had the program listed under the "forced programs" tab and it wasn't clear that I needed to add the template to force it if I was already forcing it.

It does take a while to load, even with file migration disabled but at least it is working. Closing as fixed.

**Comment by MrSmite** [comment]
Oops, clicked clicked "comment" instead of "close"...

**Comment by MrSmite** [comment]
Well, now I've started getting this error when I double-click a video:

mpc-be64.exe: SBIE2203 Failed to communicate with Sandboxie Service:  *GUIPROXY_00000001; MsgId: 19 - mpc-be64.exe [00000102]

**Comment by offhub** [comment]
Immediately after opening or after a certain period of time? I did not encounter any error messages in the virtual machine.

**Comment by MrSmite** [comment]
It happens while the player is in the process of opening the file. And it usually only happens for the first file I open right after I start my computer, occasionally it will happen for the video I open after unlocking my PC too.

It also seems to do it more often for MP4 than MKV though I don't see why. Also, the video will still play even if I let the error window stay on screen without dismissing it.

**Comment by MrSmite** [comment]
Update:

Using MPC-BE 1.6.11, it opens files fine on the local computer but if they're on a network computer the issue persists. I have MPC-BE allowed through my firewall and it works if I don't use Sandboxie.

**Comment by offhub** [comment]
Have you enabled access to network files?

**To enable access to network files:**  

1. Right-click on the Sandbox box.  
2. Select **'Sandbox Options'**.  
3. Go to **'Network Options'** > **'Other Options'**.  
4. Uncheck the box next to **'Block network files and folders unless specifically opened'**."

**Comment by MrSmite** [comment]
That option is already unchecked. But I did notice after I updated Sandboxie Plus to 1.15.11 the template under app templates was unchecked. I checked it again and everything works as expected.

The only odd behavior is two instances of MPC-BE start, one closes instantly and after a short delay the remaining one begins playing the video.
