### ISSUE TITLE
Firefox Nightly tabs crash in Sandbox since 137.0a1 (20250212110129)

### ISSUE THREAD

**Issue by 0x391F** [sandboxie-plus/Sandboxie#4522]
### Describe what you noticed and did

1. Launch Firefox Nightly in sandbox
2. Tabs always crash

### How often did you encounter it so far?

Always

### Expected behavior

This bug shouldn't appear. 

### Affected program

Latest Firefox Nightly (20250219 is 137.0a1)

### Download link

https://ftp.mozilla.org/pub/firefox/nightly/latest-mozilla-central/firefox-137.0a1.en-US.win64.installer.exe

### Where is the program located?

The program is installed both inside and outside the sandbox.

### Did the program or any related process close unexpectedly?

No, not at all.

### What version of Sandboxie are you running now?

Sandboxie-Plus v1.15.6

### Is it a new installation of Sandboxie?

I just updated Sandboxie from a previous version (I don't remember which one).

### In which sandbox type you have this problem?

In a standard isolation sandbox (yellow sandbox icon).

### Can you reproduce this problem on a new empty sandbox?

I can confirm it also on a new empty sandbox.

### What is your Windows edition and version?

Windows 11 Enterprise LTSC 2024 x64 (24H2)

### In which Windows account you have this problem?

An account with UAC protection set to Always notify.

### Please mention any installed security software

N/A. It also happens in a virtual machine without any security software

### Sandboxie.ini configuration

```ini

```

**Comment by 0x391F** [comment]
After I test in a vm, this bug first time occur in https://ftp.mozilla.org/pub/firefox/nightly/2025/02/2025-02-12-11-01-29-mozilla-central-l10n/（137.0a1 20250212110129）

**Comment by DavidXanatos** [comment]
I'm not sure what they broke bit they broke a lot, while the child processes crash when sandboxed, when I try to attach a debugger even the main process crashes, very wired

**Comment by DavidXanatos** [comment]
Can you pin point the commit which introduced the breaking change to firefox?

**Comment by DavidXanatos** [comment]
At a first glance I don't see what could cause the observed problem, so a build from before this commit works well?

**Comment by offhub** [comment]
There are also changes between the two builds:
https://hg.mozilla.org/mozilla-central/pushloghtml?startdate=11+days+ago&enddate=8+days+ago

This build does not crash.
```
7f5fd9b4d3452ee1132204bda40042e760dfeef4
``` 

This build crashes.
```
d5ed6c63e9083edcb16e118ce7fe484c61d4d71f
```

**Comment by DavidXanatos** [comment]
Very strange i build locally an ff at the d5ed6c63e9083edcb16e118ce7fe484c61d4d71f commit and it starts in a sandbox just fine but i get fielv ersion 1812 while the public nightly of 137 is 1604
also the crash is realy strange seams that combase.dll fals to allocate memory, what shoul dnot happen
so it may be an issue with the FF and it breaks the aplication heap somehow, and its already fixed in newer builds.
lets wait for the next nightly is this issue is still present

**Comment by 0x391F** [comment]
This bug now affects Firefox Beta 137.0b1.

**Comment by miru299** [comment]
Also, want to add to the comment, I am still facing issue in the latest version, 138.0a1

**Comment by Dean-Corso** [comment]
Hey Guys, I have the same problem with Firefox Nightly & Firefox Developer versions (latest). Every open tab does crash. Only way to get it work without any crash is to restart the browsers in the "Error fixing mode" so then all is working and no tab does crash. Pretty strange issue. All other Firefox based browsers working without problems in SB.

PS: I'm using SB classic version 5.70.7 on Windows 10 x64.

**Comment by offhub** [comment]
Crash in [@ mozilla::mscom::ProcessRuntime::InitializeSecurity] with SbieDll.dll / Sandboxie (Tonalio GmbH)
https://bugzilla.mozilla.org/show_bug.cgi?id=1952274

**Comment by DavidXanatos** [comment]
This needs to be fixed that said I'm not sure how the issue happens as at its root a windows API fails to allocate memory so something interferes with with the default process heap, Sandboxies uses an own Mem pool so its really a strange issue.

@offhub  are you sure that the change from 7f5fd9b4d3452ee1132204bda40042e760dfeef4 to d5ed6c63e9083edcb16e118ce7fe484c61d4d71f causes the crash?

**Comment by offhub** [comment]
I'm not sure. I based my response on the `about:buildconfig` information of the two versions. It's possible that the change was made much earlier but wasn't activated until later, which could explain the crash.

**Comment by DavidXanatos** [comment]
I have resolved the issue with commit https://github.com/sandboxie-plus/Sandboxie/commit/f4af3f8b888e4daff5df0309a459abcaa94f8266
firefox changed how the hook functions look which throw our hook routeines of, the new approche should be more robust.
