### ISSUE TITLE
Intel GPA installation error

### ISSUE THREAD

**Issue by gandalfthewhite19890404** [sandboxie-plus/Sandboxie#605]
Application - gpa_20.4.1608031112_release-external_x64_standalone.msi, obtained from official website.
OS - Windows 10.
When i trying install Intel GPA from MSI i have got error - Requires Windows 7, 8 or 8.1.
![IntelGPA_SB485](https://user-images.githubusercontent.com/24764335/108668738-c5871400-74ec-11eb-8ad6-c4cb665f0bca.jpg)

Used Sandboxie 5.48.5.
If you're create some folder and put msi there and then launch it installation goes further until actual installation progress bar but it will fail with same message.

Such behaviour is for a long time (with earlier versions of Intel GPA and sandboxie), I guess it was always on Windows 10, on Windows 7 it is installs and works.

**Comment by DavidXanatos** [comment]
could you please provide a download link

**Comment by gandalfthewhite19890404** [comment]
https://registrationcenter-download.intel.com/akdlm/irc_nas/17543/gpa_20.4.1608031112_release-external_x64_standalone.msi

**Comment by DavidXanatos** [comment]
in the next build you will be able to set 

OverrideOsBuild=7601

and this will make sbie report windows 7 sp1 to the running applications with that the install works

**Comment by gandalfthewhite19890404** [comment]
Still does not work for me, tried classic 5.49.0 and plus 0.7.2.
OverrideOsBuild=7601 was added to ini. 
Btw do we can set it in GUI?

**Comment by isaak654** [comment]
> 
> 
> Still does not work for me, tried classic 5.49.0 and plus 0.7.2.
> OverrideOsBuild=7601 was added to ini.

@DavidXanatos

It's not working here as well. I added OverrideOsBuild=7601 in GlobalSettings -> Classic 5.49.0.
I tried without success with the same msi installer provided in the first link in this topic.

**Comment by DavidXanatos** [comment]
![grafik](https://user-images.githubusercontent.com/3890945/110199402-7fb93c80-7e58-11eb-99d9-6203ca5b5f66.png)
on my system it works fine, strange that it does not work for you

**Comment by DavidXanatos** [comment]
btw don't use global settings for this option

**Comment by gandalfthewhite19890404** [comment]
Try to continue until Intel GPA gonna be installed. I unchecked Add to Explorer context menu and checked both shortcut link checkboxes.

**Comment by DavidXanatos** [comment]
please try the latest build and report back if it helped

**Comment by isaak654** [comment]
> 
> 
> please try the latest build and report back if it helped

Not working for me, I tried to create a new sandbox in Sandboxie Classic 5.49.5 and I added manually `OverrideOsBuild=7601` to the sandbox itself. So I tested the command on the same intel installer above, no result (right click on the msi file -> Run sandboxed -> I click on the 'Continue' button to go forward with the install -> the following warning appears):
![image](https://user-images.githubusercontent.com/24764335/110200280-2b20bc00-7e6e-11eb-889e-0f099cadacb2.png)

I also created a new standard sandbox on Sandboxie Plus 0.7.3 in another Windows 10 20h2 install, no luck.

**Comment by gandalfthewhite19890404** [comment]
Was it fixed in latest versions?

**Comment by isaak654** [comment]
> 
> 
> Was it fixed in latest versions?

The OverrideOsBuild setting wasn't touched since Build 0.7.3 / 5.49.5, so my previous post is still valid.

**Comment by isaak654** [comment]
Any news on this one on the upcoming 0.7.5?

**Comment by alasalto** [comment]
Freefilesync software (https://freefilesync.org/) installer shows up the same issue with SB+. It´s unable to install as of version 11.14 when using SB+ v0.96 on a Win10Pro 21H1 system. The FreeFileSync Installer refuses to install in a fresh sandbox. The error message points out to a min Windows version needed: Windows 7 or later. 
Adding 'OverrideOsBuild=7601' parameter didn't work neither.

**Comment by alasalto** [comment]
> Freefilesync software (https://freefilesync.org/) installer shows up the same issue with SB+. It´s unable to install as of version 11.14 when using SB+ v0.96 on a Win10Pro 21H1 system. The FreeFileSync Installer refuses to install in a fresh sandbox. The error message points out to a min Windows version needed: Windows 7 or later. Adding 'OverrideOsBuild=7601' parameter didn't work neither.

Testing FFF ver 11.15 still happening. The program refuses to install showing up an error dialog: "FreefileSync 11.15 requires Windows 7  or later to run"

**Comment by isaak654** [comment]
This Intel GPA installation error I reported a few posts ago results fixed here on Plus 1.0.2 and W10 21H1 x64 Pro.

**Comment by DavidXanatos** [comment]
so the issue can be closed?

**Comment by isaak654** [comment]
> so the issue can be closed?

See:

> > Adding 'OverrideOsBuild=7601' parameter didn't work neither.
> 
> That parameter never worked since the beginning. Just for the record, it was added in `Sandboxie/core/dll/userenv.c`: [48488df?diff=unified#diff-3434716960b35ef0cac23943b4c76a5a8f1fc5f60e76e5e9b3e860120ad82d4d](https://github.com/sandboxie-plus/Sandboxie/commit/48488dfec15c460b140a0c8dfefb82e0a9436e6d?diff=unified#diff-3434716960b35ef0cac23943b4c76a5a8f1fc5f60e76e5e9b3e860120ad82d4d)
> 
> I think it's just a matter to decide if fixing the not working code or undo it for good.

**Comment by DavidXanatos** [comment]
OverrideOsBuild will be fixed in the next build

**Comment by call-me-ioane** [comment]
> https://registrationcenter-download.intel.com/akdlm/irc_nas/17543/gpa_20.4.1608031112_release-external_x64_standalone.msi
> 
> or you can find it here - https://software.intel.com/content/www/us/en/develop/tools/graphics-performance-analyzers/download.html

So sorry for digging up old post, million in 1 chance do you still happen to have that exact version of intel GPA 20.4 stored on your device that you can share with me? none of the links work, official backups are no longer available. Thanks a lot!

**Comment by luigicreed** [comment]
> > https://registrationcenter-download.intel.com/akdlm/irc_nas/17543/gpa_20.4.1608031112_release-external_x64_standalone.msi
> > or you can find it here - https://software.intel.com/content/www/us/en/develop/tools/graphics-performance-analyzers/download.html
> 
> So sorry for digging up old post, million in 1 chance do you still happen to have that exact version of intel GPA 20.4 stored on your device that you can share with me? none of the links work, official backups are no longer available. Thanks a lot!

Call me crazy but I am looking for this file myself. found a reason behind needing it today.. If i find a copy i will upload link, if you happen to find one pls upload link as well. @call-me-ioane =D

**Comment by call-me-ioane** [comment]
> > > https://registrationcenter-download.intel.com/akdlm/irc_nas/17543/gpa_20.4.1608031112_release-external_x64_standalone.msi
> > > or you can find it here - https://software.intel.com/content/www/us/en/develop/tools/graphics-performance-analyzers/download.html
> > 
> > 
> > So sorry for digging up old post, million in 1 chance do you still happen to have that exact version of intel GPA 20.4 stored on your device that you can share with me? none of the links work, official backups are no longer available. Thanks a lot!
> 
> Call me crazy but I am looking for this file myself. found a reason behind needing it today.. If i find a copy i will upload link, if you happen to find one pls upload link as well. [@call-me-ioane](https://github.com/call-me-ioane) =D

Yo, here you go friend! [This forum](https://lolz.team/threads/4386766/) thread also has a [download link ](https://disk.yandex.ru/d/VZZ0wDqJOP1C3Q). Sadly, I could not manage to make it work with Battle Eye protected games. If anyone comes across this post and knows a way, let me know.
